apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: system
  labels:
    control-plane: proxy
spec:
  selector:
    matchLabels:
      control-plane: proxy
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: proxy
    spec:
      containers:
      - name: proxy
        args:
          - --api-port=8080
        image: proxy:latest
        env:
          - name: AWS_ACCESS_KEY_ID
            value: minioadmin
          - name: AWS_SECRET_ACCESS_KEY
            value: minioadmin
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: system
  labels:
    control-plane: proxy
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    control-plane: proxy
