steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-o'
    - 'xtrace'
    - '-c'
    - |
      docker pull ${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}builder:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'make'
  args:
    - 'docker-build'
    - 'docker-push'
    - 'DOCKER_REPO=${_DOCKER_REPO}'
    - 'DOCKER_IMAGE_NAME_PREFIX=${_DOCKER_IMAGE_NAME_PREFIX}'
    - 'VERSION=${_VERSION}'
    - 'OS=${_OS}'
    - 'ARCH=${_ARCH}'
images:
  - '${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}builder:latest'
