steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-o'
    - 'xtrace'
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/etcd-cluster-operator-builder:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'make'
  args:
    - 'docker-build'
    - 'docker-push'
    - 'DOCKER_REPO=gcr.io/$PROJECT_ID'
    - 'VERSION=$_VERSION'
    - 'OS=$_OS'
    - 'ARCH=$_ARCH'
images:
  - 'gcr.io/$PROJECT_ID/etcd-cluster-operator-builder:latest'
