steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --target=builder
    - --destination=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}builder:${_DOCKER_TAG}
    - --build-arg=VERSION=${_VERSION}
    - --build-arg=VERSION=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}restore-agent:${_DOCKER_TAG}
    - --cache=true
    - --cache-repo=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}cache
    - --reproducible
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --target=controller
    - --destination=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}controller:${_DOCKER_TAG}
    - --build-arg=VERSION=${_VERSION}
    - --build-arg=VERSION=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}restore-agent:${_DOCKER_TAG}
    - --cache=true
    - --cache-repo=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}cache
    - --reproducible
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --target=controller-debug
    - --destination=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}controller-debug:${_DOCKER_TAG}
    - --build-arg=VERSION=${_VERSION}
    - --build-arg=VERSION=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}restore-agent:${_DOCKER_TAG}
    - --cache=true
    - --cache-repo=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}cache
    - --reproducible
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --target=proxy
    - --destination=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}proxy:${_DOCKER_TAG}
    - --build-arg=VERSION=${_VERSION}
    - --build-arg=VERSION=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}restore-agent:${_DOCKER_TAG}
    - --cache=true
    - --cache-repo=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}cache
    - --reproducible
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --target=restore-agent
    - --destination=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}restore-agent:${_DOCKER_TAG}
    - --build-arg=VERSION=${_VERSION}
    - --build-arg=VERSION=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}restore-agent:${_DOCKER_TAG}
    - --cache=true
    - --cache-repo=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}cache
    - --reproducible
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --target=backup-agent
    - --destination=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}backup-agent:${_DOCKER_TAG}
    - --build-arg=VERSION=${_VERSION}
    - --build-arg=VERSION=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}restore-agent:${_DOCKER_TAG}
    - --cache=true
    - --cache-repo=${_DOCKER_REPO}/${_DOCKER_IMAGE_NAME_PREFIX}cache
    - --reproducible
