apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: cert-manager
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        - --proxy-url=eco-proxy.eco-system.svc
        image: controller:v0.2.0-23-gf84abc6
        name: manager
        imagePullPolicy: IfNotPresent
        
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      terminationGracePeriodSeconds: 10
