apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdPeer
metadata:
  name: etcdpeer-sample
spec:
  clusterName: bees
  version: 3.2.28
  storage:
    volumeClaimTemplate:
      storageClassName: standard
      resources:
        requests:
          storage: 50Mi
  podTemplate:
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 200Mi
