apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdRestore
metadata:
  name: etcdrestore-sample
spec:
  source:
    # See https://gocloud.dev/howto/blob/#s3-compatible for details on how this query string works.
    # And https://godoc.org/gocloud.dev/aws#ConfigFromURLParams
    objectURL: s3://foo-bucket/snapshot.sb
  clusterTemplate:
    clusterName: my-cluster
    spec:
      replicas: 3
      version: 3.2.28
      storage:
        volumeClaimTemplate:
          storageClassName: standard
          resources:
            requests:
              storage: 1Mi
      podTemplate:
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 200Mi
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: etcd.improbable.io/cluster-name
                        operator: In
                        values:
                          - my-cluster
                  topologyKey: kubernetes.io/hostname
