apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdBackupSchedule
metadata:
  name: etcdbackupschedule-sample
spec:
  schedule: "* * * * *"
  backupTemplate:
    source:
      clusterURL: http://my-cluster:2379
    destination:
      objectURL: "s3://foo-bucket/snapshot-{{ .UID }}.db"
