apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdCluster
metadata:
  name: storageos-etcd-default-sc
  namespace: storageos-etcd
spec:
  replicas: 1
  version: 3.5.3
  tls:
    enabled: true
  storage:
    volumeClaimTemplate:
      resources:
        requests:
          storage: 1Mi
  podTemplate:
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 200Mi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: etcd.improbable.io/cluster-name
                    operator: In
                    values:
                      - storageos-etcd
              topologyKey: kubernetes.io/hostname
