# The EtcdCluster here only manages the headless service required for the EtcdPeers below to bootstrap
apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdCluster
metadata:
  name: my-cluster
  namespace: default
---
apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdPeer
metadata:
  name: one
  namespace: default
spec:
  clusterName: my-cluster
  bootstrap:
    static:
      initialCluster:
      - name: one
        host: one.my-cluster.default.svc
      - name: two
        host: two.my-cluster.default.svc
      - name: three
        host: three.my-cluster.default.svc
---
apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdPeer
metadata:
  name: two
  namespace: default
spec:
  clusterName: my-cluster
  bootstrap:
    static:
      initialCluster:
      - name: one
        host: one.my-cluster.default.svc
      - name: two
        host: two.my-cluster.default.svc
      - name: three
        host: three.my-cluster.default.svc
---
apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdPeer
metadata:
  name: three
  namespace: default
spec:
  clusterName: my-cluster
  bootstrap:
    static:
      initialCluster:
      - name: one
        host: one.my-cluster.default.svc
      - name: two
        host: two.my-cluster.default.svc
      - name: three
        host: three.my-cluster.default.svc
