# A service for client access to the ETCD cluster.
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-external
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: etcd
    etcd.improbable.io/cluster-name: my-cluster
  ports:
    - protocol: TCP
      port: 2379
      nodePort: 32379
      targetPort: 2379
---
# The EtcdCluster here only manages the headless service required for the EtcdPeers below to bootstrap
apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdCluster
metadata:
  name: my-cluster
  namespace: default
---
apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdPeer
metadata:
  name: one
  namespace: default
spec:
  clusterName: my-cluster
  bootstrap:
    static:
      initialCluster:
      - name: one
        host: one.my-cluster.default.svc
      - name: two
        host: two.my-cluster.default.svc
      - name: three
        host: three.my-cluster.default.svc
---
apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdPeer
metadata:
  name: two
  namespace: default
spec:
  clusterName: my-cluster
  bootstrap:
    static:
      initialCluster:
      - name: one
        host: one.my-cluster.default.svc
      - name: two
        host: two.my-cluster.default.svc
      - name: three
        host: three.my-cluster.default.svc
---
apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdPeer
metadata:
  name: three
  namespace: default
spec:
  clusterName: my-cluster
  bootstrap:
    static:
      initialCluster:
      - name: one
        host: one.my-cluster.default.svc
      - name: two
        host: two.my-cluster.default.svc
      - name: three
        host: three.my-cluster.default.svc
