apiVersion: v1
kind: Service
metadata:
  name: magic
  namespace: default
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: etcd
    etcd.improable.io/cluster-name: magic
  ports:
    - protocol: TCP
      port: 2380
      targetPort: 2380
---
apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdPeer
metadata:
  name: one
  namespace: default
spec:
  clusterName: magic
  bootstrap:
    static:
      initialCluster:
      - name: one
        host: one.magic.default.svc
      - name: two
        host: two.magic.default.svc
      - name: three
        host: three.magic.default.svc
---
apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdPeer
metadata:
  name: two
  namespace: default
spec:
  clusterName: magic
  bootstrap:
    static:
      initialCluster:
      - name: one
        host: one.magic.default.svc
      - name: two
        host: two.magic.default.svc
      - name: three
        host: three.magic.default.svc
---
apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdPeer
metadata:
  name: three
  namespace: default
spec:
  clusterName: magic
  bootstrap:
    static:
      initialCluster:
      - name: one
        host: one.magic.default.svc
      - name: two
        host: two.magic.default.svc
      - name: three
        host: three.magic.default.svc
