// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package proxy

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BackupRequest struct {
	ClusterIdentifier    string               `protobuf:"bytes,1,opt,name=cluster_identifier,json=clusterIdentifier,proto3" json:"cluster_identifier,omitempty"`
	BackupTimestamp      *timestamp.Timestamp `protobuf:"bytes,2,opt,name=backup_timestamp,json=backupTimestamp,proto3" json:"backup_timestamp,omitempty"`
	Backup               []byte               `protobuf:"bytes,3,opt,name=backup,proto3" json:"backup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BackupRequest) Reset()         { *m = BackupRequest{} }
func (m *BackupRequest) String() string { return proto.CompactTextString(m) }
func (*BackupRequest) ProtoMessage()    {}
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *BackupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupRequest.Unmarshal(m, b)
}
func (m *BackupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupRequest.Marshal(b, m, deterministic)
}
func (m *BackupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupRequest.Merge(m, src)
}
func (m *BackupRequest) XXX_Size() int {
	return xxx_messageInfo_BackupRequest.Size(m)
}
func (m *BackupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackupRequest proto.InternalMessageInfo

func (m *BackupRequest) GetClusterIdentifier() string {
	if m != nil {
		return m.ClusterIdentifier
	}
	return ""
}

func (m *BackupRequest) GetBackupTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.BackupTimestamp
	}
	return nil
}

func (m *BackupRequest) GetBackup() []byte {
	if m != nil {
		return m.Backup
	}
	return nil
}

type BackupReply struct {
	BackupUrl            string   `protobuf:"bytes,1,opt,name=backup_url,json=backupUrl,proto3" json:"backup_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackupReply) Reset()         { *m = BackupReply{} }
func (m *BackupReply) String() string { return proto.CompactTextString(m) }
func (*BackupReply) ProtoMessage()    {}
func (*BackupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *BackupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupReply.Unmarshal(m, b)
}
func (m *BackupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupReply.Marshal(b, m, deterministic)
}
func (m *BackupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupReply.Merge(m, src)
}
func (m *BackupReply) XXX_Size() int {
	return xxx_messageInfo_BackupReply.Size(m)
}
func (m *BackupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupReply.DiscardUnknown(m)
}

var xxx_messageInfo_BackupReply proto.InternalMessageInfo

func (m *BackupReply) GetBackupUrl() string {
	if m != nil {
		return m.BackupUrl
	}
	return ""
}

type RestoreRequest struct {
	ClusterIdentifier    string   `protobuf:"bytes,1,opt,name=cluster_identifier,json=clusterIdentifier,proto3" json:"cluster_identifier,omitempty"`
	BackupUrl            string   `protobuf:"bytes,2,opt,name=backup_url,json=backupUrl,proto3" json:"backup_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreRequest) Reset()         { *m = RestoreRequest{} }
func (m *RestoreRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreRequest) ProtoMessage()    {}
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *RestoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreRequest.Unmarshal(m, b)
}
func (m *RestoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreRequest.Marshal(b, m, deterministic)
}
func (m *RestoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreRequest.Merge(m, src)
}
func (m *RestoreRequest) XXX_Size() int {
	return xxx_messageInfo_RestoreRequest.Size(m)
}
func (m *RestoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreRequest proto.InternalMessageInfo

func (m *RestoreRequest) GetClusterIdentifier() string {
	if m != nil {
		return m.ClusterIdentifier
	}
	return ""
}

func (m *RestoreRequest) GetBackupUrl() string {
	if m != nil {
		return m.BackupUrl
	}
	return ""
}

type RestoreReply struct {
	Backup               []byte   `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreReply) Reset()         { *m = RestoreReply{} }
func (m *RestoreReply) String() string { return proto.CompactTextString(m) }
func (*RestoreReply) ProtoMessage()    {}
func (*RestoreReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{3}
}

func (m *RestoreReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreReply.Unmarshal(m, b)
}
func (m *RestoreReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreReply.Marshal(b, m, deterministic)
}
func (m *RestoreReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreReply.Merge(m, src)
}
func (m *RestoreReply) XXX_Size() int {
	return xxx_messageInfo_RestoreReply.Size(m)
}
func (m *RestoreReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreReply.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreReply proto.InternalMessageInfo

func (m *RestoreReply) GetBackup() []byte {
	if m != nil {
		return m.Backup
	}
	return nil
}

func init() {
	proto.RegisterType((*BackupRequest)(nil), "proxy.BackupRequest")
	proto.RegisterType((*BackupReply)(nil), "proxy.BackupReply")
	proto.RegisterType((*RestoreRequest)(nil), "proxy.RestoreRequest")
	proto.RegisterType((*RestoreReply)(nil), "proxy.RestoreReply")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xcd, 0xca, 0x56, 0x76, 0xba, 0xfe, 0x1b, 0xff, 0x50, 0x0a, 0x62, 0xe9, 0x41, 0x7a,
	0xd0, 0x2e, 0xac, 0x82, 0x77, 0xc1, 0x83, 0x37, 0x09, 0x7a, 0x75, 0xd9, 0xae, 0xd9, 0xa5, 0x98,
	0x35, 0x31, 0x4d, 0xc4, 0x7e, 0x18, 0xbf, 0xab, 0x6c, 0x92, 0x56, 0xdb, 0xa3, 0xc7, 0xbc, 0x99,
	0x79, 0xef, 0x37, 0x13, 0x08, 0xa5, 0x12, 0x5f, 0x75, 0x2e, 0x95, 0xd0, 0x02, 0x87, 0xf6, 0x11,
	0x9f, 0xaf, 0x84, 0x58, 0x71, 0x36, 0xb1, 0x62, 0x61, 0x96, 0x13, 0x5d, 0xae, 0x59, 0xa5, 0xe7,
	0x6b, 0xe9, 0xfa, 0xd2, 0x6f, 0x02, 0xbb, 0x77, 0xf3, 0xc5, 0x9b, 0x91, 0x94, 0x7d, 0x18, 0x56,
	0x69, 0xbc, 0x02, 0x5c, 0x70, 0x53, 0x69, 0xa6, 0x66, 0xe5, 0x2b, 0x7b, 0xd7, 0xe5, 0xb2, 0x64,
	0x2a, 0x22, 0x09, 0xc9, 0x46, 0xf4, 0xd0, 0x57, 0x1e, 0xda, 0x02, 0xde, 0xc3, 0x41, 0x61, 0xe7,
	0x67, 0xad, 0x75, 0x34, 0x48, 0x48, 0x16, 0x4e, 0xe3, 0xdc, 0x85, 0xe7, 0x4d, 0x78, 0xfe, 0xd4,
	0x74, 0xd0, 0x7d, 0x37, 0xd3, 0x0a, 0x78, 0x0a, 0x81, 0x93, 0xa2, 0xed, 0x84, 0x64, 0x63, 0xea,
	0x5f, 0xe9, 0x25, 0x84, 0x0d, 0x9e, 0xe4, 0x35, 0x9e, 0x01, 0xf8, 0x34, 0xa3, 0xb8, 0x87, 0x1a,
	0x39, 0xe5, 0x59, 0xf1, 0xf4, 0x05, 0xf6, 0x28, 0xab, 0xb4, 0x50, 0xec, 0x9f, 0xdb, 0x74, 0xfd,
	0x07, 0x7d, 0xff, 0x0b, 0x18, 0xb7, 0xfe, 0x1b, 0x9c, 0x5f, 0x6a, 0xf2, 0x97, 0x7a, 0xfa, 0x09,
	0xc3, 0xc7, 0xcd, 0xfd, 0xf1, 0x06, 0x02, 0x87, 0x8f, 0xc7, 0xb9, 0xfb, 0x9e, 0xce, 0xb1, 0x63,
	0xec, 0xa9, 0x92, 0xd7, 0xe9, 0x16, 0xde, 0xc2, 0x8e, 0x8f, 0xc1, 0x13, 0xdf, 0xd0, 0x5d, 0x2b,
	0x3e, 0xea, 0xcb, 0x76, 0xb0, 0x08, 0xec, 0xa9, 0xaf, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xac,
	0x4c, 0xbf, 0x4b, 0x0b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyClient interface {
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupReply, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreReply, error)
}

type proxyClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyClient(cc grpc.ClientConnInterface) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupReply, error) {
	out := new(BackupReply)
	err := c.cc.Invoke(ctx, "/proxy.Proxy/Backup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreReply, error) {
	out := new(RestoreReply)
	err := c.cc.Invoke(ctx, "/proxy.Proxy/Restore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServer is the server API for Proxy service.
type ProxyServer interface {
	Backup(context.Context, *BackupRequest) (*BackupReply, error)
	Restore(context.Context, *RestoreRequest) (*RestoreReply, error)
}

// UnimplementedProxyServer can be embedded to have forward compatible implementations.
type UnimplementedProxyServer struct {
}

func (*UnimplementedProxyServer) Backup(ctx context.Context, req *BackupRequest) (*BackupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (*UnimplementedProxyServer) Restore(ctx context.Context, req *RestoreRequest) (*RestoreReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}

func RegisterProxyServer(s *grpc.Server, srv ProxyServer) {
	s.RegisterService(&_Proxy_serviceDesc, srv)
}

func _Proxy_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proxy.Proxy/Backup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Backup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proxy.Proxy/Restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Proxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Backup",
			Handler:    _Proxy_Backup_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _Proxy_Restore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxy.proto",
}
