name: Release Version
on:
  push:
    tags:      
      - "v*"      

jobs:
  auto-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref_name, '-alpha.') && !contains(github.ref_name, '-beta.')
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Make manifest
        run: make uber
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            storageos-etcd-cluster-operator.yaml     
            config/samples/storageos-etcd-cluster.yaml 


  auto-prerelease:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && (contains(github.ref_name, '-alpha.') || contains(github.ref_name, '-beta.'))
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Make manifest
        run: make uber
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            storageos-etcd-cluster-operator.yaml     
            config/samples/storageos-etcd-cluster.yaml 
