name: Publish develop image

on:
  push:
    branches:
      - main

jobs:
  publish-image:
    runs-on: ubuntu-latest
    name: Publish container image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.3
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_CLI_USERNAME }}
          password: ${{ secrets.DOCKERHUB_CLI_PASSWORD }}
      - name: Login to quay container registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.RED_HAT_QUAY_CLI_USERNAME }}
          password: ${{ secrets.RED_HAT_QUAY_CLI_PASSWORD }}
      - name: Build container images for docker
        run: make docker-build
      - name: Push container images to docker hub and quay
        run: make docker-push


  publish-manifests-image:
    runs-on: ubuntu-latest
    name: Publish manifests container image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_CLI_USERNAME }}
          password: ${{ secrets.DOCKERHUB_CLI_PASSWORD }}
      - name: Build manifests image 
        run: make manifests-image
      - name: Push manifests image
        run: make manifests-image-push 
